name: docs-build-deploy

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  build-and-deploy:
    if: ${{ always() }}
    name: Build and deploy documentation with makefile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Install python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      # https://github.com/actions/cache/blob/main/examples.md#python---pip
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('doc/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          pip install -r doc/requirements.txt
      - name: Call git-fleximod
        run: |
          bin/git-fleximod update -o
      # Build documentation under ${PWD}/_build
      - name: Build Sphinx docs with makefile
        run: |
          make SPHINXOPTS="-W --keep-going" BUILDDIR=${PWD}/_build -C doc/ html

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './_build/html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
